language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - nginx
    - curl
    - wget
install:
- bash -x scripts/install_nginx.sh
before_script:
- echo before script
script:
- bash -x test.sh
